name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build and Test
        run: |
          mvn clean test
        env:
          CI: true

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/junitreport.xml
      - name: Generate Cucumber Report
        run: |
          # Generate your Cucumber HTML report here
          # Replace the following line with the actual command to generate the report
          echo "Generating Cucumber HTML report"
        working-directory: target

      - name: Publish Cucumber Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-html-report
          path: target/cucumber-reports.html   
notifications:
  email:
    recipients:
      - kapildev.jagadishprasad@expleogroup.com
